- name: configuration
  hosts: all
  gather_facts: false
  become: true
  vars_files: 
    - ./open_three-tier-app.yml

  tasks:
  - name: enable repos from "{{ vars_files }}"
    yum_repository:
      name: "{{ repo.name }}"
      description: "{{ repo.description }}"
      baseurl: "{{ repo.baseurl }}"
      gpgcheck: "{{ repo.gpgcheck }}"
      mirrorlist: "{{ repo.mirrorlist | default(omit) }}"
    loop: "{{ repos_load }}"
    loop_control:
      loop_var: repo
